version: '3'
services:
  server:
#    image: darneus/cod4_v1.7_server
    build: 'server/'
    volumes:
      - ./main:/srv/cod4/main
      - ./zone:/srv/cod4/zone:ro
      - ./mods:/srv/cod4/mods
      - ./usermaps:/srv/cod4/usermaps:ro
    network_mode: bridge
    ports:
      - 28960:28960/udp
    restart: always

#  http:
#    image: httpd:alpine
#    container_name: cod4-http
#    volumes:
#      - ./mods:/usr/local/apache2/htdocs/mods:ro
#      - ./usermaps:/usr/local/apache2/htdocs/usermaps:ro
#    ports:
#      - 80
#    networks:
#      - web
#    restart: always
#
#networks:
#  web:
#    external:
#      name: nginx-proxy
